"use client";

import { useState, useEffect } from "react";

interface ComponentProps {
  inputText: string;
  onChangeInputText: (text: string) => void;
}

function toCamelCase(str: string): string {
  if (!str) return "Field";
  return str
    .split(/[-_\s]+/)
    .map(part => part.charAt(0).toUpperCase() + part.slice(1))
    .join("")
    .replace(/[^a-zA-Z0-9]/g, "");
}

function jsonToGo(jsonStr: string, structName: string = "AutoGenerated"): string {
  if (!jsonStr.trim()) return "";
  let parsed: any;
  try {
    parsed = JSON.parse(jsonStr);
  } catch (err) {
    return `// 错误: 无效的 JSON 输入\n// ${err}`;
  }

  const nestedStructs: string[] = [];
  const processedStructs = new Set<string>();

  function formatStruct(obj: any, name: string): string {
    if (processedStructs.has(name)) {
      return "";
    }
    processedStructs.add(name);

    let result = `type ${name} struct {\n`;
    
    for (const key in obj) {
      if (Object.prototype.hasOwnProperty.call(obj, key)) {
        const val = obj[key];
        const goKey = toCamelCase(key);
        let goType = "interface{}";

        if (val === null) {
          goType = "interface{}";
        } else if (typeof val === "string") {
          goType = "string";
        } else if (typeof val === "number") {
          goType = Number.isInteger(val) ? "int" : "float64";
        } else if (typeof val === "boolean") {
          goType = "bool";
        } else if (Array.isArray(val)) {
          if (val.length === 0) {
            goType = "[]interface{}";
          } else {
            const first = val[0];
            if (first === null) {
              goType = "[]interface{}";
            } else if (typeof first === "string") {
              goType = "[]string";
            } else if (typeof first === "number") {
              goType = Number.isInteger(first) ? "[]int" : "[]float64";
            } else if (typeof first === "boolean") {
              goType = "[]bool";
            } else if (typeof first === "object") {
              const singularKey = key.endsWith("s") && key.length > 1 ? key.slice(0, -1) : key;
              const subName = name + toCamelCase(singularKey);
              goType = `[]${subName}`;
              const subStruct = formatStruct(first, subName);
              if (subStruct) nestedStructs.push(subStruct);
            }
          }
        } else if (typeof val === "object") {
          const subName = name + toCamelCase(key);
          goType = subName;
          const subStruct = formatStruct(val, subName);
          if (subStruct) nestedStructs.push(subStruct);
        }

        result += `\t${goKey} ${goType} \`json:"${key}"\`\n`;
      }
    }
    result += "}";
    return result;
  }

  let goCode = "";
  if (Array.isArray(parsed)) {
    if (parsed.length === 0) {
      return `type ${structName} []interface{}`;
    }
    const first = parsed[0];
    if (typeof first === "object" && first !== null) {
      goCode = formatStruct(first, structName);
    } else {
      const typeOfFirst = typeof first === "number"
        ? (Number.isInteger(first) ? "int" : "float64")
        : typeof first;
      return `type ${structName} []${typeOfFirst}`;
    }
  } else if (typeof parsed === "object" && parsed !== null) {
    goCode = formatStruct(parsed, structName);
  } else {
    return `// 错误: JSON 根节点必须是对象或数组`;
  }

  return [goCode, ...nestedStructs.reverse()].filter(Boolean).join("\n\n");
}

export default function JsonToGoTab({ inputText, onChangeInputText }: ComponentProps) {
  const [structName, setStructName] = useState("UserResponse");
  const [copied, setCopied] = useState(false);
  const [goOutput, setGoOutput] = useState("");

  useEffect(() => {
    setGoOutput(jsonToGo(inputText, structName));
  }, [inputText, structName]);

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(goOutput);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch (e) {
      console.error(e);
    }
  };

  const handleClear = () => {
    onChangeInputText("");
    setCopied(false);
  };

  return (
    <div style={{ display: "flex", flexDirection: "column", gap: "1.5rem" }}>
      <div className="tool-toolbar" style={{ display: "flex", flexWrap: "wrap", gap: "0.5rem" }}>
        <label className="tool-field tool-field--compact" style={{ display: "flex", gap: "0.5rem", alignItems: "center" }}>
          <span>结构体根命名</span>
          <input
            type="text"
            value={structName}
            onChange={(e) => setStructName(e.target.value.replace(/[^a-zA-Z0-9_]/g, "") || "AutoGenerated")}
            style={{ width: "150px" }}
          />
        </label>
        <button
          type="button"
          className="button--primary"
          onClick={handleCopy}
          disabled={!goOutput || goOutput.startsWith("// 错误")}
        >
          {copied ? "已复制" : "复制 Go 代码"}
        </button>
        <button type="button" className="button--danger" onClick={handleClear}>
          清空
        </button>
      </div>

      <div className="workspace workspace--two-column">
        <label className="tool-field">
          <span>输入 JSON 数据</span>
          <textarea
            value={inputText}
            onChange={(e) => {
              onChangeInputText(e.target.value);
              setCopied(false);
            }}
            placeholder="请在此处粘贴 JSON 数据..."
            spellCheck={false}
            style={{ minHeight: "350px", fontFamily: "monospace" }}
          />
        </label>

        <label className="tool-field">
          <span>Go Struct 结构体定义</span>
          <textarea
            value={goOutput}
            readOnly
            placeholder="Go Struct 结构体定义将在此处生成..."
            spellCheck={false}
            style={{ minHeight: "350px", fontFamily: "monospace", background: "var(--bg-muted)" }}
          />
        </label>
      </div>

      <p className="tool-note" style={{ fontSize: "0.8rem", color: "var(--text-tertiary)" }}>
        提示：生成的 Golang 结构体支持嵌套推断，对于数组内部的复杂对象，会自动提取并命名为独立的结构体；类型推断会自动区分 <strong>int</strong> 与 <strong>float64</strong>。
      </p>
    </div>
  );
}
