"use client";

import { useState } from "react";
import type { ToolAppProps } from "@tool-platform/tool-contracts";

const JSON_SAMPLE = `{
  "id": 1024,
  "username": "golang_developer",
  "is_admin": true,
  "profile": {
    "first_name": "Jack",
    "last_name": "Chen",
    "avatar_url": "https://example.com/avatar.png"
  },
  "login_ips": ["192.168.1.1", "127.0.0.1"],
  "projects": [
    {
      "project_id": 99,
      "project_name": "Tool Platform",
      "completion_rate": 88.5
    }
  ]
}`;

function toCamelCase(str: string): string {
  if (!str) return "Field";
  return str
    .split(/[-_\s]+/)
    .map(part => part.charAt(0).toUpperCase() + part.slice(1))
    .join("")
    .replace(/[^a-zA-Z0-9]/g, "");
}

function jsonToGo(jsonStr: string, structName: string = "AutoGenerated"): string {
  let parsed: any;
  try {
    parsed = JSON.parse(jsonStr);
  } catch (err) {
    return `// 错误: 无效的 JSON 输入\n// ${err}`;
  }

  const nestedStructs: string[] = [];
  const processedStructs = new Set<string>();

  function formatStruct(obj: any, name: string): string {
    if (processedStructs.has(name)) {
      return "";
    }
    processedStructs.add(name);

    let result = `type ${name} struct {\n`;
    
    for (const key in obj) {
      if (Object.prototype.hasOwnProperty.call(obj, key)) {
        const val = obj[key];
        const goKey = toCamelCase(key);
        let goType = "interface{}";

        if (val === null) {
          goType = "interface{}";
        } else if (typeof val === "string") {
          goType = "string";
        } else if (typeof val === "number") {
          goType = Number.isInteger(val) ? "int" : "float64";
        } else if (typeof val === "boolean") {
          goType = "bool";
        } else if (Array.isArray(val)) {
          if (val.length === 0) {
            goType = "[]interface{}";
          } else {
            const first = val[0];
            if (first === null) {
              goType = "[]interface{}";
            } else if (typeof first === "string") {
              goType = "[]string";
            } else if (typeof first === "number") {
              goType = Number.isInteger(first) ? "[]int" : "[]float64";
            } else if (typeof first === "boolean") {
              goType = "[]bool";
            } else if (typeof first === "object") {
              // Singularize sub-struct name if keys ends with 's' (e.g. projects -> Project)
              const singularKey = key.endsWith("s") && key.length > 1 ? key.slice(0, -1) : key;
              const subName = name + toCamelCase(singularKey);
              goType = `[]${subName}`;
              const subStruct = formatStruct(first, subName);
              if (subStruct) nestedStructs.push(subStruct);
            }
          }
        } else if (typeof val === "object") {
          const subName = name + toCamelCase(key);
          goType = subName;
          const subStruct = formatStruct(val, subName);
          if (subStruct) nestedStructs.push(subStruct);
        }

        result += `\t${goKey} ${goType} \`json:"${key}"\`\n`;
      }
    }
    result += "}";
    return result;
  }

  let goCode = "";
  if (Array.isArray(parsed)) {
    if (parsed.length === 0) {
      return `type ${structName} []interface{}`;
    }
    const first = parsed[0];
    if (typeof first === "object" && first !== null) {
      goCode = formatStruct(first, structName);
    } else {
      const typeOfFirst = typeof first === "number"
        ? (Number.isInteger(first) ? "int" : "float64")
        : typeof first;
      return `type ${structName} []${typeOfFirst}`;
    }
  } else if (typeof parsed === "object" && parsed !== null) {
    goCode = formatStruct(parsed, structName);
  } else {
    return `// 错误: JSON 根节点必须是对象或数组`;
  }

  return [goCode, ...nestedStructs.reverse()].filter(Boolean).join("\n\n");
}

export default function JsonToGoTool({ manifest }: ToolAppProps) {
  const [jsonInput, setJsonInput] = useState(JSON_SAMPLE);
  const [structName, setStructName] = useState("UserResponse");
  const [copied, setCopied] = useState(false);

  const goOutput = jsonToGo(jsonInput, structName);

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(goOutput);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch (e) {
      console.error(e);
    }
  };

  const handleClear = () => {
    setJsonInput("");
    setCopied(false);
  };

  return (
    <section className="tool-panel">
      <div className="tool-panel__header">
        <div>
          <p className="eyebrow">开发与数据建模</p>
          <h2>{manifest.name}</h2>
        </div>
        <p>{manifest.description}</p>
      </div>

      {/* Preset Toolbar */}
      <div className="tool-toolbar" style={{ display: "flex", flexWrap: "wrap", gap: "0.5rem", marginBottom: "1rem" }}>
        <div style={{ display: "flex", gap: "0.5rem", flex: 1 }}>
          <button type="button" className="button--secondary" onClick={() => setJsonInput(JSON_SAMPLE)}>
            加载 JSON 示例
          </button>
        </div>
        <div style={{ display: "flex", gap: "0.5rem", alignItems: "center" }}>
          <label style={{ fontSize: "0.85rem", color: "var(--text-secondary)", marginRight: "0.2rem" }}>结构体根命名</label>
          <input
            type="text"
            value={structName}
            onChange={(e) => setStructName(e.target.value.replace(/[^a-zA-Z0-9_]/g, "") || "AutoGenerated")}
            style={{ width: "130px", background: "var(--bg-muted)", height: "30px", padding: "0 0.5rem", fontSize: "0.85rem" }}
          />
          <button type="button" className="button--danger" onClick={handleClear}>
            清空
          </button>
        </div>
      </div>

      {/* Main workspace */}
      <div className="workspace workspace--two-column">
        {/* JSON Input Pane */}
        <label className="tool-field">
          <span>输入 JSON 数据</span>
          <textarea
            value={jsonInput}
            onChange={(e) => {
              setJsonInput(e.target.value);
              setCopied(false);
            }}
            placeholder="请在此处粘贴 JSON 数据..."
            spellCheck={false}
            style={{ height: "360px", fontFamily: "monospace", resize: "vertical" }}
          />
        </label>

        {/* Go Struct Output Pane */}
        <label className="tool-field">
          <span style={{ display: "flex", justifyContent: "space-between", alignItems: "center" }}>
            Go Struct 结构体定义
            <button
              type="button"
              onClick={handleCopy}
              disabled={!goOutput || goOutput.startsWith("// 错误")}
              style={{ fontSize: "0.75rem", padding: "0.1rem 0.4rem", height: "auto" }}
            >
              {copied ? "已复制" : "复制"}
            </button>
          </span>
          <textarea
            value={goOutput}
            readOnly
            placeholder="Go Struct 结构体定义将在此处生成..."
            spellCheck={false}
            style={{ height: "360px", fontFamily: "monospace", resize: "vertical" }}
          />
        </label>
      </div>

      <p className="tool-note" style={{ marginTop: "1.2rem" }}>
        提示：生成的 Golang 结构体支持嵌套推断，对于数组内部的复杂对象，会自动提取并命名为独立的结构体；类型推断会自动区分 <strong>int</strong> 与 <strong>float64</strong>。
      </p>
    </section>
  );
}
